name: Latest Blog Posts
on:
  schedule:
    # Runs every 5 minutes
    - cron: '0 * * * *'

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
<<<<<<< HEAD
          feed_list: "https://dev.to/shivajipotnuru"
=======
          # comment_tag_name: "STACKOVERFLOW"
          # commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://dev.to/shivajipotnuru"
>>>>>>> 65ee9f2b82610bb85301dfe5196659548ae180e3
